package com.suatkkrer.taboo_android

import androidx.appcompat.app.AppCompatActivity
import android.os.Bundle
import android.view.View
import kotlinx.android.synthetic.main.activity_taboo.*
import java.util.ArrayList

class TabooActivity : AppCompatActivity() {

    var tabooList = ArrayList<WordModel>()

    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)
        setContentView(R.layout.activity_taboo)
        window.decorView.systemUiVisibility = View.SYSTEM_UI_FLAG_FULLSCREEN
        actionBar?.hide()


        tabooList.add(WordModel("FİİL","İŞ","OLUŞ","HAREKET","EYLEM","SÖZCÜK"))
        tabooList.add(WordModel("UYAK", "ŞİİR", "DİZE", "BENZERLİK", "KAFİYE", "SES"))
        tabooList.add(WordModel("SÖZLÜK","ANLAM","KELİME","SÖZCÜK","AÇIKLAMA","LÜGAT"))
        tabooList.add(WordModel("KUŞBAKIŞI ","HARİTA","TEPE","YUKARI","GÖRMEK","KROKİ"))
        tabooList.add(WordModel("OKKA","AĞIRLIK","ÖLÇÜ","BİRİM","KİLO","TARTI"))
        tabooList.add(WordModel("KÖK","SÖZCÜK","YAPIM","ÇEKİM","EK","KELİME"))
        tabooList.add(WordModel("ŞİİR","ŞAİR","MISRA","DİZE","KITA","DÖRTLÜK"))
        tabooList.add(WordModel("8)\tÖYKÜ","HİKÂYE","KAHRAMAN","YAZAR","YER","KİTAP"))
        tabooList.add(WordModel("14)\tMASAL","OLAĞANÜSTÜ","KAHRAMAN","YAZAR","KELOĞLAN","KİTAP"))
        tabooList.add(WordModel("15)\tFAY","HAT","DEPREM","KIRILMAK","SARSILMAK","İSTANBUL"))
        tabooList.add(WordModel("16)\tKÜÇÜMSEME","NİTELİK","DEĞERSİZ","YARGI","CÜMLE","AZIMSAMA"))
        tabooList.add(WordModel("17)\tPARAGRAF","SINAV","SORU","ANA DÜŞÜNCE","YARDIMCI DÜŞÜNCE","METİN"))
        tabooList.add(WordModel("18)\tMETRES","KARI KOCA","EVLİ","ALDATMAK","YASAK","İLİŞKİ"))
        tabooList.add(WordModel("19)\tFAX","ÇEKMEK","GÖNDERMEK","YAZI","KAĞIT","FOTOKOPİ"))
        tabooList.add(WordModel("20)\tGAZİ","SAVAŞ","YARALANMAK","ŞEHİT","İSTİKLAL MADALYASI","ATATÜRK"))
        tabooList.add(WordModel("VEKTÖR","YÖN","FİZİK","SKALER","ÇİZMEK","DOĞRU"))
        tabooList.add(WordModel("HASIRALTI ETMEK","SAKLAMAK","GİZLEMEK","KORUMAK","YOK ETMEK","ÖRTBAS"))
        tabooList.add(WordModel("24)\tVENEDİK","GONDOL","ÜLKE","SU","İTALYA","YÜZMEK"))
        tabooList.add(WordModel("25)\tSELÜLİT","BACAK","KADIN","CİLT","YAĞ","PORTAKAL"))
        tabooList.add(WordModel("26)\tNORM","KURAL","YERLEŞMİŞ","İLKE","YASA","DÜZEN"))
        tabooList.add(WordModel("27)\tALT","ÜST","YER","TABAN","DERECE","SINIF"))
        tabooList.add(WordModel("28)\tABONE","YONCA EVCİMİK","SATIN ALMAK","ÜYE","DERGİ","GAZETE"))
        tabooList.add(WordModel("29)\tTEZGAH","KURMAK","MASA","MUTFAK","SATICI","BÜFE"))
        tabooList.add(WordModel("30)\tTEMAS","FİZİKSEL","DEĞME","DOKUNMA","MÜNASEBET","BULUŞMAK"))
        tabooList.add(WordModel("31)\tEFSANE","HAYALİ","YARADILIŞ","ÖYKÜ","ABARTMAK","SÖYLENCE"))
        tabooList.add(WordModel("32)\tİMLA","KURAL","YAZIM","DİL BİLGİSİ","HATA","TERİM"))
        tabooList.add(WordModel("33)\tSAKAL","KIL","YÜZ","TIRAŞ","KESMEK","TOP"))
        tabooList.add(WordModel("34)\tLOSYON","TIRAŞ","KOLONYA","PARFÜM","KOKU","BERBER"))
        tabooList.add(WordModel("35)\tBARBAR","KABA","İLKEL","KIRICI","UYGARLAŞMA","AKIN"))
        tabooList.add(WordModel("36)\tFABL","MASAL","HAYVAN","HİKAYE","ÖYKÜ","DERS"))
        tabooList.add(WordModel("37)\tABDESTHANE","TUVALET","WC","HELA","YÜZNUMARA","ALMAK"))
        tabooList.add(WordModel("38)\tHAKİ","RENK","YEŞİL","KAHVERENGİ","ÇALMAK","KAÇMAK"))
        tabooList.add(WordModel("39)\tLATİN AMERİKA","GÜNEY","KITA","BREZİLYA","ÜLKE","ARJANTİN"))
        tabooList.add(WordModel("40)\tDEFİNE","HARİTA","PARA","ALTIN","ALİ","BABA"))
        tabooList.add(WordModel("41)\tTARAMAK","SAÇ","ARAŞTIRMAK","DERLEMEK","ATEŞLEMEK","AYIKLAMAK"))
        tabooList.add(WordModel("42)\tİPUCU","İZ","EMARE","VERMEK","DEDEKTİF","SIR"))
        tabooList.add(WordModel("43)\tALTIN","TAKMAK","DEĞERLİ","KUYUMCU","SARRAF","ÇEYREK"))
        tabooList.add(WordModel("44)\tAÇISAL HIZ","FİZİK","VEKTÖREL","HAREKET","DAİRESEL","TARAMAK"))
        tabooList.add(WordModel("45)\tSÜZMEK","SU","AYIRMAK","SIVI","MAKARNA","KATI"))
        tabooList.add(WordModel("46)\tKABAKULAK","HASTALIK","İLTİHAP","ŞİŞMEK","BEZ","TÜKÜRÜK"))
        tabooList.add(WordModel("47)\tKÜF","EKMEK","YEŞİL","MANTAR","BAKTERİ","KURT"))
        tabooList.add(WordModel("48)\tANATOMİ","VÜCUT","SİSTEM","İNCELEMEK","ORGAN","DİŞ"))
        tabooList.add(WordModel("49)\tKARL MARX","SOSYALİZM","KOMÜNİZM","FELSEFE","MANİFESTO","KAPİTAL"))
        tabooList.add(WordModel("50)\tHALAY ÇEKMEK","DÜĞÜN","OYNAMAK","DAİRE","MENDİL","BAŞ"))
        tabooList.add(WordModel("51)\tALTERNATİF AKIM","DOĞRU","ELEKTRİK","DEĞİŞKEN","NİKOLA TESLA","SİNÜS"))
        tabooList.add(WordModel("52)\tFOTOKOPİ","KOPYA","MAKİNE","FAX","TARAMAK","KIRTASİYE"))
        tabooList.add(WordModel("53)\tBARKOD","ÜRÜN","FİYAT","İMZA","ÇİZGİ","ALT"))
        tabooList.add(WordModel("54)\tODAK","OPTİK","IŞIK","KAYNAK","TOPLANMAK","MİHRAK"))
        tabooList.add(WordModel("55)\tMAKAS","KUMAŞ","KESMEK","KAĞIT","NİŞAN","TERZİ"))
        tabooList.add(WordModel("57)\tKANTİN","OKUL ","TOST ","KAFETERYA ","ÖĞRENCİ ","YEMEK"))
        tabooList.add(WordModel("58)\tİMA ETMEK","ANLAM ","İZ ","DURUM ","DAVRANIŞ ","ALAMET"))
        tabooList.add(WordModel("59)\tMÜHİMMAT","DEPO ","SAVAŞ ","CEPHANE ","ORDU ","SİLAH"))
        tabooList.add(WordModel("60)\tHIÇKIRIK","SES ","TUTMAK ","DİYAFRAM ","SU ","NEFES"))
        tabooList.add(WordModel("61)\tBUZ DEVRİ","ESKİ ÇAĞ","SOĞUK ","ERİMEK ","KAR ","ÇİZGİ FİLM"))
        tabooList.add(WordModel("62)\tSALSA","SOS ","DANS ","LATİN ","İSPANYOL ","PARTİ"))
        tabooList.add(WordModel("63)\tBONCUK","KOLYE ","TAKI ","RENKLİ ","KÜÇÜK ","YUVARLAK"))
        tabooList.add(WordModel("64)\tTRAVESTİ","ERKEK ","KADIN ","TRANSSEKSÜEL ","KILIK ","GİRMEK"))
        tabooList.add(WordModel("65)\tDAKTİLO","YAZMAK ","HARF ","KAĞIT ","TUŞ ","STİLO"))
        tabooList.add(WordModel("66)\tTELSİZ","TELEFON ","KONUŞMAK ","POLİS ","İLETİŞİM ","BASMAK"))
        tabooList.add(WordModel("67)\tSANDAL","MOTOR ","DENİZ ","KÜREK ","SEFA ","BALIKÇI"))
        tabooList.add(WordModel("68)\tABLUKA","KUŞATMA ","SARMAK ","ÇEVRELEMEK ","ALMAK ","KAPLAMAK"))
        tabooList.add(WordModel("69)\tHAÇ","HRİSTİYANLIK ","ÇAĞLA ŞİKEL","ARTI İŞARETİ","İSA ","ÇARMIH"))
        tabooList.add(WordModel("70)\tASİT","MAVİ ","KIRMIZI ","TURNUSOL ","BAZ ","MİDE"))
        tabooList.add(WordModel("71)\tKUŞ BAKIŞI","YÜKSEK ","GENEL ","HAYVAN ","GÖRMEK ","ALAN"))
        tabooList.add(WordModel("72)\tHATIR","GÖNÜL  ","KALP ","HAFIZA ","ZİHİN ","KIRMAK"))
        tabooList.add(WordModel("73)\tİMRENMEK","KISKANMAK ","GIPTA ETMEK","ÖZENMEK ","CANI ÇEKMEK","İSTEMEK"))
        tabooList.add(WordModel("74)\tDUMUR","KÖRELMEK ","APTALLAŞMAK ","ŞOK OLMAK ","ŞAŞIRMAK ","ŞAŞKINA DÖNMEK"))
        tabooList.add(WordModel("75)\tKAHIR","MAHVETME ","PERİŞAN ","EZME ","ÇEKMEK ","ETMEK"))
        tabooList.add(WordModel("76)\tKÖŞK","BAHÇE ","EV ","SÜSLÜ ","KASİR ","YAPI"))
        tabooList.add(WordModel("77)\tALYANS","EVLİLİK ","YÜZÜK ","KARIKOCA ","PARMAK ","TAKMAK"))
        tabooList.add(WordModel("78)\tİKTİDAR","OTORİTE ","MUHALEFET ","YETKİ ","KUVVET ","PARTİ"))
        tabooList.add(WordModel("ÇIBAN","İRİN ","DERİ ","BİRİKMEK ","VÜCUT ","ÇIKMAK"))
        tabooList.add(WordModel("ARAP","SİYAH ","AFRİKA ","FELLAH ","SABUN ","BACI"))
        tabooList.add(WordModel("KALSİYUM","KEMİK ","SÜT ","PEYNİR ","YOĞURT ","DİŞ"))
        tabooList.add(WordModel("ÇAYIR","OTLAMAK ","İNEK ","YEŞİL ","ÇİMEN ","PİKNİK"))
        tabooList.add(WordModel("KLİMA","SICAK ","DUVAR ","YAZ ","SOBA ","KALORİFER"))
        tabooList.add(WordModel("BALİNA","DENİZ","MEMELİ ","HAYVAN ","YUNUS","SU "))
        tabooList.add(WordModel("OLUMSUZ","NEGATİF ","ZARARLI ","UYGUN ","YAPICI ","YARARLI"))
        tabooList.add(WordModel("MİSYONER","DİN ","YAYMAK ","HRİSTİYAN ","ADAMAK ","DÜŞÜNCE"))
        tabooList.add(WordModel("SİNCAP","HAYVAN ","KEMİRMEK ","AĞAÇ ","FINDIK ","KOKARCA"))
        tabooList.add(WordModel("RAMAZAN BAYRAMI","ŞEKER ","KUTLAMAK ","KURBAN BAYRAMI ","TATİL ","DİNİ"))
        tabooList.add(WordModel("FARENJİT","HASTALIK ","BOĞAZ ","İLTİHAP ","TOZ ","SPREY"))
        tabooList.add(WordModel("ARSA","YER ","ALAN ","YAPI ","TARLA ","YAPMAK"))
        tabooList.add(WordModel("SAÇ","FÖN ","KUAFÖR BERBER ","KADIN ERKEK ","KESTİRMEK","BOYATMAK"))
        tabooList.add(WordModel("HARE","PARLAK ","ÇİZGİ ","DALGA ","SERT ","KUMAŞ"))
        tabooList.add(WordModel("BİLİNÇ","ŞUUR ","TANIMA ","BİLGİ ","GÖRÜŞ ","TEMEL"))
        tabooList.add(WordModel("KALABALIK","İNSAN ","ÇOK ","TOPLULUK ","KARGAŞA ","AŞIRI"))
        tabooList.add(WordModel("SOĞUK ALGINLIĞI","ÜŞÜTMEK ","HASTALIK ","ATEŞ ","NEZLE ","AKINTI"))
        tabooList.add(WordModel("MUTASYON","DEĞİŞİM ","EVRİM ","FARKLI ","GEÇİRMEK ","GEN"))
        tabooList.add(WordModel("NELSON MANDELA","SİYAHİ  ","AFRİKA  ","TUTUKLU  ","BAŞKAN ","LİDER"))
        tabooList.add(WordModel("UZAK DURMAK","YAKLAŞMAMAK ","İSTEMEMEK ","MESAFE ","KOYMAK ","YAKIN"))
        tabooList.add(WordModel("DENEY","KİMYA ","LABORATUVAR ","FARE ","BİLİM ","TÜP"))
        tabooList.add(WordModel("PÜSKÜL","SAÇAK ","İP ","SÜS ","FES ","MISIR"))
        tabooList.add(WordModel("EMBESİL","ZEKA GERİLİĞİ","APTAL ","AHMAK ","SALAK ","MORON"))
        tabooList.add(WordModel("BEDDUA","KÖTÜLÜK ","TUTMAK ","ALMAK ","ETMEK ","BELA"))
        tabooList.add(WordModel("DÖNME DOLAP","LUNAPARK ","YÜKSEK ","ÇOCUK ","EĞLENCE ","OTURMAK"))
        tabooList.add(WordModel("BABA","ERKEK","MAFYA","AİLE","ÇOCUK","ANNE"))
        tabooList.add(WordModel("GAZETE","BASIN","OKUMAK","MEDYA","İLAN","SAYFA"))
        tabooList.add(WordModel("KARATE","DÖVÜŞ SANATLARI","YUMRUK","TEKME","KİD","KAVGA"))
        tabooList.add(WordModel("CAMİ","İMAM","NAMAZ","MÜSLÜMAN","CEMAAT","İBADET"))
        tabooList.add(WordModel("TERLİK","AYAKKABI","HAFİF","ANNE","GİYMEK","EV"))
        tabooList.add(WordModel("ÖRMEK","ŞİŞ","YÜN","KAZAK","DANTEL","ATKI"))
        tabooList.add(WordModel("KLİMA","KALORİFER","SOĞUK","DUVAR","YAZ","SICAK"))
        tabooList.add(WordModel("ÜNİVERSİTE","OKUL","ÖSS","FAKÜLTE","EĞİTİM","ÖĞRENCİ"))
        tabooList.add(WordModel("KRAVAT","GÖMLEK","TAKIM ELBİSE","MEDENİYET YULARI","BOYUN","YAKA"))
        tabooList.add(WordModel("FASULYE","PİLAV","KURU","GAZ","SIRIK","YEMEK"))
        tabooList.add(WordModel("DEDE KORKUT","EFSANE","ERGENEKON","DESTAN","HİKAYE","ESKİ"))
        tabooList.add(WordModel("ALTIN","DEĞERLİ","SARRAF","ÇEYREK","TAKMAK","KUYUMCU"))
        tabooList.add(WordModel("TAHAMÜL ETMEK","SABIR","DAYANMAK","ARTIK","SINIR","KATLANMAK"))
        tabooList.add(WordModel("SALDIRGAN","AGRESİF","TEHLİKE","KAVGA","ZARAR","DÜŞMAN"))
        tabooList.add(WordModel("ŞİKAYET","HOŞNUTSUZ","MEMNUNİYET","YAKINMAK","TÜKETİCİ","DERT"))
        tabooList.add(WordModel("MEŞALE","ATEŞ","IŞIK","AYDINLIK","YAKMAK","OLİMPİYAT"))
        tabooList.add(WordModel("UYUZ","BULAŞICI","GICIK ETMEK","KÖPEK","HASTALIK","KAŞINMAK"))
        tabooList.add(WordModel("BEZE","HAMUR","YAĞ","PASTA","PİŞKİNLİK","PAZ"))
        tabooList.add(WordModel("TOSBAĞA","VOSVOS","ARABA","KABUK","KAPLUMBAĞA","ESKİ"))
        tabooList.add(WordModel("BÖCEK","ZEHİR","SİNEK","HAŞERE","HAYVAN","YARATIK"))
        tabooList.add(WordModel("YATAKHANE","YATILI","YURT","KIŞLA","OKUL","YATMAK"))
        tabooList.add(WordModel("UZLAŞMAK","İŞBİRLİĞİ","MUTABAKAT","UYUŞMA","ANLAŞMA","İTTİFAK"))
        tabooList.add(WordModel("MAKİNİST","METRO","SİNEMA","FİLM","TREN","KULLANMAK"))
        tabooList.add(WordModel("AYDINLATMAK","GÖRÜNMEK","IŞIK","BİLGİLENDİRMEK","KARANLIK","GİDERMEK"))
        tabooList.add(WordModel("ÇALMAK","POLİS","HIRSIZ","ARANMAK","İZİN","EV"))
        tabooList.add(WordModel("ÇATLAK","ARALIK","AYRILMAK","DELİ","ARA","YARILMAK"))
        tabooList.add(WordModel("asdfa","asdfasdf","asdfasf","asfasgd","asdgsadg","asdgasg"))
        tabooList.add(WordModel("asdfa","asdfasdf","asdfasf","asfasgd","asdgsadg","asdgasg"))
        tabooList.add(WordModel("asdfa","asdfasdf","asdfasf","asfasgd","asdgsadg","asdgasg"))
        tabooList.add(WordModel("asdfa","asdfasdf","asdfasf","asfasgd","asdgsadg","asdgasg"))
        tabooList.add(WordModel("asdfa","asdfasdf","asdfasf","asfasgd","asdgsadg","asdgasg"))
        tabooList.add(WordModel("asdfa","asdfasdf","asdfasf","asfasgd","asdgsadg","asdgasg"))
        tabooList.add(WordModel("asdfa","asdfasdf","asdfasf","asfasgd","asdgsadg","asdgasg"))
        tabooList.add(WordModel("asdfa","asdfasdf","asdfasf","asfasgd","asdgsadg","asdgasg"))
        tabooList.add(WordModel("asdfa","asdfasdf","asdfasf","asfasgd","asdgsadg","asdgasg"))
        tabooList.add(WordModel("asdfa","asdfasdf","asdfasf","asfasgd","asdgsadg","asdgasg"))
        tabooList.add(WordModel("asdfa","asdfasdf","asdfasf","asfasgd","asdgsadg","asdgasg"))
        tabooList.add(WordModel("asdfa","asdfasdf","asdfasf","asfasgd","asdgsadg","asdgasg"))
        tabooList.add(WordModel("asdfa","asdfasdf","asdfasf","asfasgd","asdgsadg","asdgasg"))
        tabooList.add(WordModel("asdfa","asdfasdf","asdfasf","asfasgd","asdgsadg","asdgasg"))
        tabooList.add(WordModel("asdfa","asdfasdf","asdfasf","asfasgd","asdgsadg","asdgasg"))
        tabooList.add(WordModel("asdfa","asdfasdf","asdfasf","asfasgd","asdgsadg","asdgasg"))
        tabooList.add(WordModel("asdfa","asdfasdf","asdfasf","asfasgd","asdgsadg","asdgasg"))
        tabooList.add(WordModel("asdfa","asdfasdf","asdfasf","asfasgd","asdgsadg","asdgasg"))
        tabooList.add(WordModel("asdfa","asdfasdf","asdfasf","asfasgd","asdgsadg","asdgasg"))
        tabooList.add(WordModel("asdfa","asdfasdf","asdfasf","asfasgd","asdgsadg","asdgasg"))
        tabooList.add(WordModel("asdfa","asdfasdf","asdfasf","asfasgd","asdgsadg","asdgasg"))
        tabooList.add(WordModel("asdfa","asdfasdf","asdfasf","asfasgd","asdgsadg","asdgasg"))
        tabooList.add(WordModel("asdfa","asdfasdf","asdfasf","asfasgd","asdgsadg","asdgasg"))
        tabooList.add(WordModel("asdfa","asdfasdf","asdfasf","asfasgd","asdgsadg","asdgasg"))
        tabooList.add(WordModel("asdfa","asdfasdf","asdfasf","asfasgd","asdgsadg","asdgasg"))
        tabooList.add(WordModel("asdfa","asdfasdf","asdfasf","asfasgd","asdgsadg","asdgasg"))
        tabooList.add(WordModel("asdfa","asdfasdf","asdfasf","asfasgd","asdgsadg","asdgasg"))
        tabooList.add(WordModel("asdfa","asdfasdf","asdfasf","asfasgd","asdgsadg","asdgasg"))
        tabooList.add(WordModel("asdfa","asdfasdf","asdfasf","asfasgd","asdgsadg","asdgasg"))
        tabooList.add(WordModel("asdfa","asdfasdf","asdfasf","asfasgd","asdgsadg","asdgasg"))
        tabooList.add(WordModel("asdfa","asdfasdf","asdfasf","asfasgd","asdgsadg","asdgasg"))
        tabooList.add(WordModel("asdfa","asdfasdf","asdfasf","asfasgd","asdgsadg","asdgasg"))
        tabooList.add(WordModel("asdfa","asdfasdf","asdfasf","asfasgd","asdgsadg","asdgasg"))
        tabooList.add(WordModel("asdfa","asdfasdf","asdfasf","asfasgd","asdgsadg","asdgasg"))
        tabooList.add(WordModel("asdfa","asdfasdf","asdfasf","asfasgd","asdgsadg","asdgasg"))
        tabooList.add(WordModel("asdfa","asdfasdf","asdfasf","asfasgd","asdgsadg","asdgasg"))
        tabooList.add(WordModel("asdfa","asdfasdf","asdfasf","asfasgd","asdgsadg","asdgasg"))
        tabooList.add(WordModel("asdfa","asdfasdf","asdfasf","asfasgd","asdgsadg","asdgasg"))
        tabooList.add(WordModel("asdfa","asdfasdf","asdfasf","asfasgd","asdgsadg","asdgasg"))
        tabooList.add(WordModel("asdfa","asdfasdf","asdfasf","asfasgd","asdgsadg","asdgasg"))
        tabooList.add(WordModel("asdfa","asdfasdf","asdfasf","asfasgd","asdgsadg","asdgasg"))
        tabooList.add(WordModel("asdfa","asdfasdf","asdfasf","asfasgd","asdgsadg","asdgasg"))
        tabooList.add(WordModel("asdfa","asdfasdf","asdfasf","asfasgd","asdgsadg","asdgasg"))
        tabooList.add(WordModel("asdfa","asdfasdf","asdfasf","asfasgd","asdgsadg","asdgasg"))
        tabooList.add(WordModel("asdfa","asdfasdf","asdfasf","asfasgd","asdgsadg","asdgasg"))
        tabooList.add(WordModel("asdfa","asdfasdf","asdfasf","asfasgd","asdgsadg","asdgasg"))
        tabooList.add(WordModel("asdfa","asdfasdf","asdfasf","asfasgd","asdgsadg","asdgasg"))
        tabooList.add(WordModel("asdfa","asdfasdf","asdfasf","asfasgd","asdgsadg","asdgasg"))
        tabooList.add(WordModel("asdfa","asdfasdf","asdfasf","asfasgd","asdgsadg","asdgasg"))
        tabooList.add(WordModel("asdfa","asdfasdf","asdfasf","asfasgd","asdgsadg","asdgasg"))
        tabooList.add(WordModel("asdfa","asdfasdf","asdfasf","asfasgd","asdgsadg","asdgasg"))
        tabooList.add(WordModel("asdfa","asdfasdf","asdfasf","asfasgd","asdgsadg","asdgasg"))
        tabooList.add(WordModel("asdfa","asdfasdf","asdfasf","asfasgd","asdgsadg","asdgasg"))
        tabooList.add(WordModel("asdfa","asdfasdf","asdfasf","asfasgd","asdgsadg","asdgasg"))
        tabooList.add(WordModel("asdfa","asdfasdf","asdfasf","asfasgd","asdgsadg","asdgasg"))
        tabooList.add(WordModel("asdfa","asdfasdf","asdfasf","asfasgd","asdgsadg","asdgasg"))
        tabooList.add(WordModel("asdfa","asdfasdf","asdfasf","asfasgd","asdgsadg","asdgasg"))
        tabooList.add(WordModel("asdfa","asdfasdf","asdfasf","asfasgd","asdgsadg","asdgasg"))
        tabooList.add(WordModel("asdfa","asdfasdf","asdfasf","asfasgd","asdgsadg","asdgasg"))
        tabooList.add(WordModel("asdfa","asdfasdf","asdfasf","asfasgd","asdgsadg","asdgasg"))
        tabooList.add(WordModel("asdfa","asdfasdf","asdfasf","asfasgd","asdgsadg","asdgasg"))
        tabooList.add(WordModel("asdfa","asdfasdf","asdfasf","asfasgd","asdgsadg","asdgasg"))
        tabooList.add(WordModel("asdfa","asdfasdf","asdfasf","asfasgd","asdgsadg","asdgasg"))
        tabooList.add(WordModel("asdfa","asdfasdf","asdfasf","asfasgd","asdgsadg","asdgasg"))
        tabooList.add(WordModel("asdfa","asdfasdf","asdfasf","asfasgd","asdgsadg","asdgasg"))
        tabooList.add(WordModel("asdfa","asdfasdf","asdfasf","asfasgd","asdgsadg","asdgasg"))
        tabooList.add(WordModel("asdfa","asdfasdf","asdfasf","asfasgd","asdgsadg","asdgasg"))
        tabooList.add(WordModel("asdfa","asdfasdf","asdfasf","asfasgd","asdgsadg","asdgasg"))
        tabooList.add(WordModel("asdfa","asdfasdf","asdfasf","asfasgd","asdgsadg","asdgasg"))
        tabooList.add(WordModel("asdfa","asdfasdf","asdfasf","asfasgd","asdgsadg","asdgasg"))
        tabooList.add(WordModel("asdfa","asdfasdf","asdfasf","asfasgd","asdgsadg","asdgasg"))
        tabooList.add(WordModel("asdfa","asdfasdf","asdfasf","asfasgd","asdgsadg","asdgasg"))
        tabooList.add(WordModel("asdfa","asdfasdf","asdfasf","asfasgd","asdgsadg","asdgasg"))
        tabooList.add(WordModel("asdfa","asdfasdf","asdfasf","asfasgd","asdgsadg","asdgasg"))
        tabooList.add(WordModel("asdfa","asdfasdf","asdfasf","asfasgd","asdgsadg","asdgasg"))
        tabooList.add(WordModel("asdfa","asdfasdf","asdfasf","asfasgd","asdgsadg","asdgasg"))
        tabooList.add(WordModel("asdfa","asdfasdf","asdfasf","asfasgd","asdgsadg","asdgasg"))
        tabooList.add(WordModel("asdfa","asdfasdf","asdfasf","asfasgd","asdgsadg","asdgasg"))
        tabooList.add(WordModel("asdfa","asdfasdf","asdfasf","asfasgd","asdgsadg","asdgasg"))
        tabooList.add(WordModel("asdfa","asdfasdf","asdfasf","asfasgd","asdgsadg","asdgasg"))
        tabooList.add(WordModel("asdfa","asdfasdf","asdfasf","asfasgd","asdgsadg","asdgasg"))
        tabooList.add(WordModel("asdfa","asdfasdf","asdfasf","asfasgd","asdgsadg","asdgasg"))
        tabooList.add(WordModel("asdfa","asdfasdf","asdfasf","asfasgd","asdgsadg","asdgasg"))
        tabooList.add(WordModel("asdfa","asdfasdf","asdfasf","asfasgd","asdgsadg","asdgasg"))
        tabooList.add(WordModel("asdfa","asdfasdf","asdfasf","asfasgd","asdgsadg","asdgasg"))
        tabooList.add(WordModel("asdfa","asdfasdf","asdfasf","asfasgd","asdgsadg","asdgasg"))
        tabooList.add(WordModel("asdfa","asdfasdf","asdfasf","asfasgd","asdgsadg","asdgasg"))
        tabooList.add(WordModel("asdfa","asdfasdf","asdfasf","asfasgd","asdgsadg","asdgasg"))
        tabooList.add(WordModel("asdfa","asdfasdf","asdfasf","asfasgd","asdgsadg","asdgasg"))
        tabooList.add(WordModel("asdfa","asdfasdf","asdfasf","asfasgd","asdgsadg","asdgasg"))
        tabooList.add(WordModel("asdfa","asdfasdf","asdfasf","asfasgd","asdgsadg","asdgasg"))
        tabooList.add(WordModel("asdfa","asdfasdf","asdfasf","asfasgd","asdgsadg","asdgasg"))
        tabooList.add(WordModel("asdfa","asdfasdf","asdfasf","asfasgd","asdgsadg","asdgasg"))
        tabooList.add(WordModel("asdfa","asdfasdf","asdfasf","asfasgd","asdgsadg","asdgasg"))
        tabooList.add(WordModel("asdfa","asdfasdf","asdfasf","asfasgd","asdgsadg","asdgasg"))
        tabooList.add(WordModel("asdfa","asdfasdf","asdfasf","asfasgd","asdgsadg","asdgasg"))
        tabooList.add(WordModel("asdfa","asdfasdf","asdfasf","asfasgd","asdgsadg","asdgasg"))
        tabooList.add(WordModel("asdfa","asdfasdf","asdfasf","asfasgd","asdgsadg","asdgasg"))
        tabooList.add(WordModel("asdfa","asdfasdf","asdfasf","asfasgd","asdgsadg","asdgasg"))
        tabooList.add(WordModel("asdfa","asdfasdf","asdfasf","asfasgd","asdgsadg","asdgasg"))
        tabooList.add(WordModel("asdfa","asdfasdf","asdfasf","asfasgd","asdgsadg","asdgasg"))
        tabooList.add(WordModel("asdfa","asdfasdf","asdfasf","asfasgd","asdgsadg","asdgasg"))
        tabooList.add(WordModel("asdfa","asdfasdf","asdfasf","asfasgd","asdgsadg","asdgasg"))
        tabooList.add(WordModel("asdfa","asdfasdf","asdfasf","asfasgd","asdgsadg","asdgasg"))
        tabooList.add(WordModel("asdfa","asdfasdf","asdfasf","asfasgd","asdgsadg","asdgasg"))
        tabooList.add(WordModel("asdfa","asdfasdf","asdfasf","asfasgd","asdgsadg","asdgasg"))
        tabooList.add(WordModel("asdfa","asdfasdf","asdfasf","asfasgd","asdgsadg","asdgasg"))
        tabooList.add(WordModel("asdfa","asdfasdf","asdfasf","asfasgd","asdgsadg","asdgasg"))
        tabooList.add(WordModel("asdfa","asdfasdf","asdfasf","asfasgd","asdgsadg","asdgasg"))
        tabooList.add(WordModel("asdfa","asdfasdf","asdfasf","asfasgd","asdgsadg","asdgasg"))
        tabooList.add(WordModel("asdfa","asdfasdf","asdfasf","asfasgd","asdgsadg","asdgasg"))
        tabooList.add(WordModel("asdfa","asdfasdf","asdfasf","asfasgd","asdgsadg","asdgasg"))
        tabooList.add(WordModel("asdfa","asdfasdf","asdfasf","asfasgd","asdgsadg","asdgasg"))
        tabooList.add(WordModel("asdfa","asdfasdf","asdfasf","asfasgd","asdgsadg","asdgasg"))
        tabooList.add(WordModel("asdfa","asdfasdf","asdfasf","asfasgd","asdgsadg","asdgasg"))
        tabooList.add(WordModel("asdfa","asdfasdf","asdfasf","asfasgd","asdgsadg","asdgasg"))
        tabooList.add(WordModel("asdfa","asdfasdf","asdfasf","asfasgd","asdgsadg","asdgasg"))
        tabooList.add(WordModel("asdfa","asdfasdf","asdfasf","asfasgd","asdgsadg","asdgasg"))
        tabooList.add(WordModel("asdfa","asdfasdf","asdfasf","asfasgd","asdgsadg","asdgasg"))
        tabooList.add(WordModel("asdfa","asdfasdf","asdfasf","asfasgd","asdgsadg","asdgasg"))
        tabooList.add(WordModel("asdfa","asdfasdf","asdfasf","asfasgd","asdgsadg","asdgasg"))
        tabooList.add(WordModel("asdfa","asdfasdf","asdfasf","asfasgd","asdgsadg","asdgasg"))
        tabooList.add(WordModel("asdfa","asdfasdf","asdfasf","asfasgd","asdgsadg","asdgasg"))
        tabooList.add(WordModel("asdfa","asdfasdf","asdfasf","asfasgd","asdgsadg","asdgasg"))
        tabooList.add(WordModel("asdfa","asdfasdf","asdfasf","asfasgd","asdgsadg","asdgasg"))
        tabooList.add(WordModel("asdfa","asdfasdf","asdfasf","asfasgd","asdgsadg","asdgasg"))
        tabooList.add(WordModel("asdfa","asdfasdf","asdfasf","asfasgd","asdgsadg","asdgasg"))
        tabooList.add(WordModel("asdfa","asdfasdf","asdfasf","asfasgd","asdgsadg","asdgasg"))
        tabooList.add(WordModel("asdfa","asdfasdf","asdfasf","asfasgd","asdgsadg","asdgasg"))
        tabooList.add(WordModel("asdfa","asdfasdf","asdfasf","asfasgd","asdgsadg","asdgasg"))
        tabooList.add(WordModel("asdfa","asdfasdf","asdfasf","asfasgd","asdgsadg","asdgasg"))
        tabooList.add(WordModel("asdfa","asdfasdf","asdfasf","asfasgd","asdgsadg","asdgasg"))
        tabooList.add(WordModel("asdfa","asdfasdf","asdfasf","asfasgd","asdgsadg","asdgasg"))
        tabooList.add(WordModel("asdfa","asdfasdf","asdfasf","asfasgd","asdgsadg","asdgasg"))
        tabooList.add(WordModel("asdfa","asdfasdf","asdfasf","asfasgd","asdgsadg","asdgasg"))
        tabooList.add(WordModel("asdfa","asdfasdf","asdfasf","asfasgd","asdgsadg","asdgasg"))
        tabooList.add(WordModel("asdfa","asdfasdf","asdfasf","asfasgd","asdgsadg","asdgasg"))
        tabooList.add(WordModel("asdfa","asdfasdf","asdfasf","asfasgd","asdgsadg","asdgasg"))
        tabooList.add(WordModel("asdfa","asdfasdf","asdfasf","asfasgd","asdgsadg","asdgasg"))
        tabooList.add(WordModel("asdfa","asdfasdf","asdfasf","asfasgd","asdgsadg","asdgasg"))
        tabooList.add(WordModel("asdfa","asdfasdf","asdfasf","asfasgd","asdgsadg","asdgasg"))
        tabooList.add(WordModel("asdfa","asdfasdf","asdfasf","asfasgd","asdgsadg","asdgasg"))
        tabooList.add(WordModel("asdfa","asdfasdf","asdfasf","asfasgd","asdgsadg","asdgasg"))
        tabooList.add(WordModel("asdfa","asdfasdf","asdfasf","asfasgd","asdgsadg","asdgasg"))
        tabooList.add(WordModel("asdfa","asdfasdf","asdfasf","asfasgd","asdgsadg","asdgasg"))
        tabooList.add(WordModel("asdfa","asdfasdf","asdfasf","asfasgd","asdgsadg","asdgasg"))
        tabooList.add(WordModel("asdfa","asdfasdf","asdfasf","asfasgd","asdgsadg","asdgasg"))
        tabooList.add(WordModel("asdfa","asdfasdf","asdfasf","asfasgd","asdgsadg","asdgasg"))
        tabooList.add(WordModel("asdfa","asdfasdf","asdfasf","asfasgd","asdgsadg","asdgasg"))
        tabooList.add(WordModel("asdfa","asdfasdf","asdfasf","asfasgd","asdgsadg","asdgasg"))
        tabooList.add(WordModel("asdfa","asdfasdf","asdfasf","asfasgd","asdgsadg","asdgasg"))
        tabooList.add(WordModel("asdfa","asdfasdf","asdfasf","asfasgd","asdgsadg","asdgasg"))
        tabooList.add(WordModel("asdfa","asdfasdf","asdfasf","asfasgd","asdgsadg","asdgasg"))
        tabooList.add(WordModel("asdfa","asdfasdf","asdfasf","asfasgd","asdgsadg","asdgasg"))
        tabooList.add(WordModel("asdfa","asdfasdf","asdfasf","asfasgd","asdgsadg","asdgasg"))
        tabooList.add(WordModel("asdfa","asdfasdf","asdfasf","asfasgd","asdgsadg","asdgasg"))
        tabooList.add(WordModel("asdfa","asdfasdf","asdfasf","asfasgd","asdgsadg","asdgasg"))
        tabooList.add(WordModel("asdfa","asdfasdf","asdfasf","asfasgd","asdgsadg","asdgasg"))
        tabooList.add(WordModel("asdfa","asdfasdf","asdfasf","asfasgd","asdgsadg","asdgasg"))
        tabooList.add(WordModel("asdfa","asdfasdf","asdfasf","asfasgd","asdgsadg","asdgasg"))
        tabooList.add(WordModel("asdfa","asdfasdf","asdfasf","asfasgd","asdgsadg","asdgasg"))
        tabooList.add(WordModel("asdfa","asdfasdf","asdfasf","asfasgd","asdgsadg","asdgasg"))
        tabooList.add(WordModel("asdfa","asdfasdf","asdfasf","asfasgd","asdgsadg","asdgasg"))
        tabooList.add(WordModel("asdfa","asdfasdf","asdfasf","asfasgd","asdgsadg","asdgasg"))
        tabooList.add(WordModel("asdfa","asdfasdf","asdfasf","asfasgd","asdgsadg","asdgasg"))
        tabooList.add(WordModel("asdfa","asdfasdf","asdfasf","asfasgd","asdgsadg","asdgasg"))
        tabooList.add(WordModel("asdfa","asdfasdf","asdfasf","asfasgd","asdgsadg","asdgasg"))
        tabooList.add(WordModel("asdfa","asdfasdf","asdfasf","asfasgd","asdgsadg","asdgasg"))
        tabooList.add(WordModel("asdfa","asdfasdf","asdfasf","asfasgd","asdgsadg","asdgasg"))
        tabooList.add(WordModel("asdfa","asdfasdf","asdfasf","asfasgd","asdgsadg","asdgasg"))
        tabooList.add(WordModel("asdfa","asdfasdf","asdfasf","asfasgd","asdgsadg","asdgasg"))
        tabooList.add(WordModel("asdfa","asdfasdf","asdfasf","asfasgd","asdgsadg","asdgasg"))
        tabooList.add(WordModel("asdfa","asdfasdf","asdfasf","asfasgd","asdgsadg","asdgasg"))
        tabooList.add(WordModel("asdfa","asdfasdf","asdfasf","asfasgd","asdgsadg","asdgasg"))
        tabooList.add(WordModel("asdfa","asdfasdf","asdfasf","asfasgd","asdgsadg","asdgasg"))
        tabooList.add(WordModel("asdfa","asdfasdf","asdfasf","asfasgd","asdgsadg","asdgasg"))
        tabooList.add(WordModel("asdfa","asdfasdf","asdfasf","asfasgd","asdgsadg","asdgasg"))

        kelimeMain.text = tabooList[0].anaKelime
        kelime1.text = tabooList[0].kelime1
        kelime2.text = tabooList[0].kelime2
        kelime3.text = tabooList[0].kelime3
        kelime4.text = tabooList[0].kelime4
        kelime5.text = tabooList[0].kelime5



    }
}